apiVersion: apps/v1
kind: Deployment
metadata:
  name: tolerations-demo
  namespace: default
  labels:
    app.kubernetes.io/name: tolerations-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tolerations-demo
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tolerations-demo
    spec:
      # 容忍度
      tolerations:
      - key: k1
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      affinity:
        # 节点亲和性
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      restartPolicy: Always
      containers:
      - name: tolerations-demo
        image: banma24678/etcd:latest
        imagePullPolicy: Always
        command:
        - cat
        tty: true
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: "100m"
            memory: 100Mi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
